### PR TITLE
bump rocks from 0.16.0 to 0.17.0

### PR DESCRIPTION
**Pull request by TakoB222**

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Thanks for the PR @TakoB222!

Can you also ensure that the folders have the `tox.ini` files and folder with tests, so that the CI can get triggered?

**Comment by TakoB222** [comment]
> Thanks for the PR @TakoB222!
> 
> Can you also ensure that the folders have the `tox.ini` files and folder with tests, so that the CI can get triggered?

Okay, will do!

**Comment by kimwnasptd** [comment]
@TakoB222 I realised I need to push a PR to enable the CI in this repo. Doing this ASAP and will ping you back to rebase to the latest `main` branch, to see if the CI gets triggered

**Comment by kimwnasptd** [comment]
@TakoB222 could you rebase on top of the latest master, which should now have the necessary CI from https://github.com/canonical/katib-rocks/pull/47?

**Comment by TakoB222** [comment]
> @TakoB222 could you rebase on top of the latest master, which should now have the necessary CI from #47?

Yes, sure!

**Review by kimwnasptd — APPROVED** [review]

**Comment by kimwnasptd** [comment]
Thanks for the PR @TakoB222! All the tests are now passing!

**Pull request merged**
